# Generated by Skyramp v1.3.17 on 2026-06-13 16:31:32.141689184 +0000 UTC m=+322.989146307
# Command: skyramp generate contract rest http://localhost:3001/api/v1/settings/api \
# 		--auth-type token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/gitea-testb/gitea-testb/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-data {"max_response_items":50,"default_paging_num":30,"default_git_trees_per_page":1000,"default_max_blob_size":10485760,"default_max_response_size":104857600,"enable_swagger":true} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:3001")

# contract test for /api/v1/settings/api GET
def test_api_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_api_GET_response_body = r'''{
        "default_git_trees_per_page": 1000,
        "default_max_blob_size": 10485760,
        "default_max_response_size": 104857600,
        "default_paging_num": 30,
        "enable_swagger": true,
        "max_response_items": 50
    }'''

    # Execute Request
    api_GET_response = client.send_request(
        url=URL,
        path="/api/v1/settings/api",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert api_GET_response.status_code == 200
    assert skyramp.check_schema(api_GET_response, expected_api_GET_response_body)
    assert skyramp.get_response_value(api_GET_response, "default_git_trees_per_page") is not None
    assert skyramp.get_response_value(api_GET_response, "default_max_blob_size") is not None
    assert skyramp.get_response_value(api_GET_response, "default_max_response_size") is not None
    assert skyramp.get_response_value(api_GET_response, "enable_swagger") is not None
    assert skyramp.get_response_value(api_GET_response, "enable_swagger") == True
    assert skyramp.get_response_value(api_GET_response, "max_response_items") is not None
    assert skyramp.get_response_value(api_GET_response, "max_response_items") >= 0
    assert skyramp.get_response_value(api_GET_response, "default_paging_num") is not None
    assert skyramp.get_response_value(api_GET_response, "default_paging_num") >= 0
    assert skyramp.get_response_value(api_GET_response, "default_git_trees_per_page") >= 0
    assert skyramp.get_response_value(api_GET_response, "default_max_blob_size") >= 0
    assert skyramp.get_response_value(api_GET_response, "default_max_response_size") >= 0


if __name__ == "__main__":
    test_api_get()
