# Generated by Skyramp v1.3.17 on 2026-06-13 16:30:58.880665359 +0000 UTC m=+268.039661682
# Command: skyramp generate integration rest \
# 		--auth-type token \
# 		--framework pytest \
# 		--language python \
# 		--output markup_unique_constraint_integration_test.py \
# 		--output-dir /home/runner/work/gitea-testb/gitea-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/gitea-testb/gitea-testb/tests/skyramp/scenario_markup-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:3001")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    markup_POST_request_body = r'''{
        "Context": "",
        "FilePath": "",
        "Mode": "markdown",
        "Text": "Hello **World** unique constraint test",
        "Wiki": false
    }'''
    
    # Execute Request
    markup_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/markup",
        method="POST",
        body=markup_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert markup_POST_response.status_code == 201

    # Request Body
    markup_POST_1_request_body = r'''{
        "Context": "",
        "FilePath": "",
        "Mode": "markdown",
        "Text": "Hello **World** unique constraint test",
        "Wiki": false
    }'''
    
    # Execute Request
    markup_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/markup",
        method="POST",
        body=markup_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert markup_POST_1_response.status_code == 409


if __name__ == "__main__":
    test_integration()
