# Generated by Skyramp v1.3.17 on 2026-06-13 16:30:56.77461128 +0000 UTC m=+265.933607593
# Command: skyramp generate integration rest \
# 		--auth-type token \
# 		--framework pytest \
# 		--language python \
# 		--output markdown_unique_constraint_integration_test.py \
# 		--output-dir /home/runner/work/gitea-testb/gitea-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/gitea-testb/gitea-testb/tests/skyramp/scenario_markdown-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:3001")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    v1 = "markdown"

    # Request Body
    v1_POST_request_body = r'''{
        "Context": "",
        "Mode": "markdown",
        "Text": "Hello **World** unique constraint test",
        "Wiki": false
    }'''
    
    # Execute Request
    v1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/{v1}",
        method="POST",
        body=v1_POST_request_body,
        headers=headers,
        path_params={"v1": v1},
        data_override={"Mode": v1}
    )
    # Generated Assertions
    assert v1_POST_response.status_code == 201

    # Request Body
    v1_POST_1_request_body = r'''{
        "Context": "",
        "Mode": "markdown",
        "Text": "Hello **World** unique constraint test",
        "Wiki": false
    }'''
    
    # Execute Request
    v1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/{v1}",
        method="POST",
        body=v1_POST_1_request_body,
        headers=headers,
        path_params={"v1": v1},
        data_override={"Mode": v1}
    )
    # Generated Assertions
    assert v1_POST_1_response.status_code == 409


if __name__ == "__main__":
    test_integration()
