# Generated by Skyramp v1.3.17 on 2026-06-13 16:31:14.292068959 +0000 UTC m=+305.139526092
# Command: skyramp generate contract rest http://localhost:3001/api/v1/markup \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/gitea-testb/gitea-testb/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--request-data {"text":"**Hello World**","mode":"comment","type":"markdown"} \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:3001")

# contract test for /api/v1/markup POST
def test_markup_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    markup_POST_request_body = r'''{
        "mode": "comment",
        "text": "**Hello World**",
        "type": "markdown"
    }'''

    # Execute Request
    markup_POST_response = client.send_request(
        url=URL,
        path="/api/v1/markup",
        method="POST",
        body=markup_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert markup_POST_response.status_code == 401


if __name__ == "__main__":
    test_markup_post()
