# Generated by Skyramp v1.3.17 on 2026-06-13 16:31:16.344178608 +0000 UTC m=+307.191635731
# Command: skyramp generate contract rest http://localhost:3001/api/v1/user/actions/runners/registration-token \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/gitea-testb/gitea-testb/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:3001")

# contract test for /api/v1/user/actions/runners/registration-token POST
def test_registration_token_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    registration_token_POST_response = client.send_request(
        url=URL,
        path="/api/v1/user/actions/runners/registration-token",
        method="POST",
        headers=headers
    )

    # Generated Assertions
    assert registration_token_POST_response.status_code == 401


if __name__ == "__main__":
    test_registration_token_post()
