# Generated by Skyramp v1.3.17 on 2026-06-13 16:31:00.517980805 +0000 UTC m=+269.676977128
# Command: skyramp generate integration rest \
# 		--auth-type token \
# 		--framework pytest \
# 		--language python \
# 		--output registration_token_unique_constraint_integration_test.py \
# 		--output-dir /home/runner/work/gitea-testb/gitea-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/gitea-testb/gitea-testb/tests/skyramp/scenario_registration-token-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:3001")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    registration_token_POST_request_body = r'''{}'''
    
    # Execute Request
    registration_token_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/admin/actions/runners/registration-token",
        method="POST",
        body=registration_token_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert registration_token_POST_response.status_code == 201
    assert skyramp.get_response_value(registration_token_POST_response, "token") is not None

    # Request Body
    registration_token_POST_1_request_body = r'''{}'''

    # Execute Request
    registration_token_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/admin/actions/runners/registration-token",
        method="POST",
        body=registration_token_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert registration_token_POST_1_response.status_code == 409


if __name__ == "__main__":
    test_integration()
